logSavePath: storage/logs
logFileName: app
logFileExt: .log
writeTimeout: 60
readTimeout: 60
defaultContextTimeout: 60
#runMode: release debug test
runMode: debug
uploadPath: /tmp/charts
helmRepos:
#  - name: bitnami
#    url: https://charts.bitnami.com/bitnami
